apiVersion: v1
name: geist-iot
version: 0.0.1
description: The base stack of applications for the on cluster deployment of the geist-iot platform
type: application
keywords:
  - iot
  - geist
  - kafka
  - opcua
  - nuxt
  - redpanda
home: https://github.com/doteich
dependencies: # A list of the chart requirements (optional)
  - name: operator
    version: v25.1.3
    repository: https://charts.redpanda.com
  - name: questdb
    version: 1.0.11
    repository: https://helm.questdb.io
    condition: timeseries.enabled
maintainers: # (optional)
  - name: Max Eichhorn
    email: geist@geist-iot.com
