apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gualoggers.doteich.com
spec:
  group: doteich.com
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                connection:
                  type: object
                  properties:
                    endpoint:
                      type: string
                    port:
                      type: integer
                    mode:
                      type: string
                      enum:
                        - None
                        - Sign
                        - SignAndEncrypt
                    policy:
                      type: string
                      enum:
                        - None
                        - Basic256
                        - Basic256Sha256
                        - Aes256Sha256RsaPss
                        - Aes128Sha256RsaOaep
                    authentication:
                      type: object
                      properties:
                        type:
                          type: string
                          enum:
                            - None
                            - User&Password
                            - Certificate
                        credentials:
                          type: object
                          properties:
                            username:
                              type: string
                            password:
                              type: string
                        certificate:
                          type: object
                          properties:
                            certificate_path:
                              type: string
                            private_key_path:
                              type: string
                    certificate:
                      type: object
                      properties:
                        auto_create:
                          type: boolean
                        certificate_path:
                          type: string
                        private_key_path:
                          type: string
                    retry_count:
                      type: integer
                  required:
                    - endpoint
                    - port
                    - mode
                    - policy
                    - authentication
                    - certificate
                subscription:
                  type: object
                  properties:
                    sub_interval:
                      type: integer
                    nodeids:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          meta:
                            type: array
                            items:
                              type: object
                              properties:
                                key:
                                  type: string
                                value:
                                  type: string
                  required:
                    - sub_interval
                    - nodeids
                exporters:
                  type: object
                  properties:
                    timescale-db:
                      type: object
                      properties:
                        host:
                          type: string
                        port:
                          type: integer
                        username:
                          type: string
                        password:
                          type: string
                        database:
                          type: string
                        table:
                          type: string
                      required:
                        - host
                        - port
                        - username
                        - password
                        - database
                        - table
                    websocket:
                      type: object
                      properties:
                        endpoint:
                          type: string
                        port:
                          type: integer
                        username:
                          type: string
                        password:
                          type: string
                      required:
                        - endpoint
                        - port
                        - username
                        - password
                    mqtt:
                      type: object
                      properties:
                        protocol:
                          type: string
                          enum:
                            - mqtt
                            - mqtts
                        protocol_version:
                          type: integer
                        host:
                          type: string
                        port:
                          type: integer
                        username:
                          type: string
                        password:
                          type: string
                        topic:
                          type: string
                        client_id:
                          type: string
                        qos:
                          type: integer
                        retain:
                          type: boolean
                        topic_by_nodeid:
                          type: boolean
                      required:
                        - protocol
                        - protocol_version
                        - host
                        - port
                        - topic
                        - client_id
                        - qos
                        - retain
                kube:
                  type: object
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string
                    labels:
                      type: object
                      additionalProperties:
                        type: string
                    annotations:
                      type: object
                      additionalProperties:
                        type: string
                    image:
                      type: object
                      properties:
                        repository:
                          type: string
                        version:
                          type: string
                        pullPolicy:
                          type: string
                  required:
                    - namespace
                    - name
  scope: Namespaced
  names:
    plural: gualoggers
    singular: gualogger
    kind: GuaLogger
    shortNames:
      - gual