opcua:
  connection:
    endpoint: 127.0.0.1
    port: 49320
    mode: "SignAndEncrypt"   # Possible Entries: 'None', 'Sign', 'SignAndEncrypt'
    policy: 'Basic256Sha256' # Possible Entries: 'None', 'Basic256', 'Basic256Sha256', 'Aes256Sha256RsaPss', 'Aes128Sha256RsaOaep'
    authentication:
      type: 'None'           # Possible Entries: 'None', 'User&Password', 'Certificate'
      credentials:           # Only necessary if type is 'User&Password'
        username: ''
        password: ''
      certificate:           # Only necessary if type is 'Certificate'
        certificate_path: '' # absolute path to certificate file pem encoded
        private_key_path: '' # absolute path to private key file pem encoded
    certificate:             # Only necessary if mode is 'Sign' or 'SignAndEncrypt'
        auto_create: true    # if true, the application will create a self-signed cert on startup, external provided certs are ignored
        certificate_path: '' # absolute path to certificate file used for signing/encryption pem encoded - 
        private_key_path: '' # absolute path to private key file used for signing/encryption pem encoded
    retry_count: 10          # Number of Retries the the connection should retried to the server
  subscription:
    sub_interval: 10         # Subcription Interval in Seconds           
    nodeids:                 # List of Node IDs
      - i=2258
exporters:                   # Map Struct of Exporters - Work in Progress
  timescale-db:
    host: hostname
    port: 5432
    username: username
    password: password
    database: database
    table: gualogger
  websocket:
    endpoint: /ws
    port: 80
    username: username      # Specified Username, which will be used to create the base64 encoded secret to authenticate the ws client to the server - format b64(user:password)
    password: password      # Specified Password, which will be used to create the base64 encoded secret to authenticate the ws client to the server - format b64(user:password)