// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium gualoggers.doteich.com -A
// kopium version: 0.21.2

#[allow(unused_imports)]
mod prelude {
    pub use kube::CustomResource;
    pub use schemars::JsonSchema;
    pub use serde::{Serialize, Deserialize};
    pub use std::collections::BTreeMap;
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug, JsonSchema)]
#[kube(group = "doteich.com", version = "v1alpha", kind = "GuaLogger", plural = "gualoggers")]
#[kube(namespaced)]
pub struct GuaLoggerSpec {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kube: Option<GuaLoggerKube>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub logger: Option<GuaLoggerLogger>,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct GuaLoggerKube {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<GuaLoggerKubeImage>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
    pub namespace: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct GuaLoggerKubeImage {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "pullPolicy")]
    pub pull_policy: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub repository: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    pub(crate) value: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct GuaLoggerLogger {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub connection: Option<GuaLoggerLoggerConnection>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exporters: Option<GuaLoggerLoggerExporters>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subscription: Option<GuaLoggerLoggerSubscription>,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct GuaLoggerLoggerConnection {
    pub authentication: GuaLoggerLoggerConnectionAuthentication,
    pub certificate: GuaLoggerLoggerConnectionCertificate,
    pub endpoint: String,
    pub mode: GuaLoggerLoggerConnectionMode,
    pub policy: GuaLoggerLoggerConnectionPolicy,
    pub port: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub retry_count: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct GuaLoggerLoggerConnectionAuthentication {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub credentials: Option<GuaLoggerLoggerConnectionAuthenticationCredentials>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub r#type: Option<GuaLoggerLoggerConnectionAuthenticationType>,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct GuaLoggerLoggerConnectionAuthenticationCredentials {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub certificate: Option<GuaLoggerLoggerConnectionAuthenticationCredentialsCertificate>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct GuaLoggerLoggerConnectionAuthenticationCredentialsCertificate {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub certificate_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub private_key_path: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub enum GuaLoggerLoggerConnectionAuthenticationType {
    None,
    #[serde(rename = "User&Password")]
    UserPassword,
    Certificate,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct GuaLoggerLoggerConnectionCertificate {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auto_create: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub certificate_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub private_key_path: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub enum GuaLoggerLoggerConnectionMode {
    None,
    Sign,
    SignAndEncrypt,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub enum GuaLoggerLoggerConnectionPolicy {
    None,
    Basic256,
    Basic256Sha256,
    Aes256Sha256RsaPss,
    Aes128Sha256RsaOaep,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct GuaLoggerLoggerExporters {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mqtt: Option<GuaLoggerLoggerExportersMqtt>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "timescale-db")]
    pub timescale_db: Option<GuaLoggerLoggerExportersTimescaleDb>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub websocket: Option<GuaLoggerLoggerExportersWebsocket>,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct GuaLoggerLoggerExportersMqtt {
    pub client_id: String,
    pub host: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    pub port: i64,
    pub protocol: GuaLoggerLoggerExportersMqttProtocol,
    pub protocol_version: i64,
    pub qos: i64,
    pub retain: bool,
    pub topic: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic_by_nodeid: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub enum GuaLoggerLoggerExportersMqttProtocol {
    #[serde(rename = "mqtt")]
    Mqtt,
    #[serde(rename = "mqtts")]
    Mqtts,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct GuaLoggerLoggerExportersTimescaleDb {
    pub database: String,
    pub host: String,
    pub password: String,
    pub port: i64,
    pub table: String,
    pub username: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct GuaLoggerLoggerExportersWebsocket {
    pub endpoint: String,
    pub password: String,
    pub port: i64,
    pub username: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct GuaLoggerLoggerSubscription {
    pub nodeids: Vec<GuaLoggerLoggerSubscriptionNodeids>,
    pub sub_interval: i64,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct GuaLoggerLoggerSubscriptionNodeids {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<Vec<GuaLoggerLoggerSubscriptionNodeidsMeta>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct GuaLoggerLoggerSubscriptionNodeidsMeta {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

